"""Post-process the rendered shots and write film/assets/3d/manifest.json + manifest.js.
  * Masters are PNG sequences in /tmp/blender-shots/<name>/ (written by the shot scripts).
  * flythrough (opaque) -> JPG q90;  RGBA shots -> 256-colour palette PNG with alpha
    (~10x smaller than the truecolour master, visually identical for this flat toon look).
  * manifest.js (window.SHOTS3D_MANIFEST) is what film/boot.js loads. The manifest carries no start time:
    each shot's start is {ch, at} in film/timeline.js ("shots3d"), so re-timing the film never touches this.
Run with the venv python (needs Pillow):  /tmp/bpyenv/bin/python tools/blender/finalize.py
  --manifest-only   only rewrite the manifests from the frames already in film/assets/3d (no re-encode)
"""
import json, os, sys
from PIL import Image

FILM = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'film'))
OUT = os.path.join(FILM, 'assets', '3d')

SHOTS = [
    # name, alpha, ext, placement suggestion in the 1920x1080 stage, note (start: film/timeline.js shots3d)
    dict(name='flythrough', alpha=False, ext='jpg', x=0, y=0, w=1920, h=1080,
         note='t=0-2.4 opener: through the red curtains to Noa waving; last frame frames the proscenium for a crossfade'),
    dict(name='photobooth', alpha=True, ext='png', x=1120, y=170, w=740, h=740,
         note='Soul ID beat: booth pops in, 3 flashes, photo strip chugs out'),
    dict(name='coinfunnel', alpha=True, ext='png', x=590, y=140, w=740, h=740,
         note='Revenue: coins whirl down the funnel, bounce into a pile, hero coin leaps at camera'),
    dict(name='curtaincall', alpha=True, ext='png', x=0, y=0, w=1920, h=1080,
         note='Curtain call: ta-da, rippling bow, Noa tips shades + winks, confetti (transparent bg)'),
]


def main():
    manifest_only = '--manifest-only' in sys.argv
    manifest = []
    for s in SHOTS:
        d = os.path.join(OUT, s['name'])
        os.makedirs(d, exist_ok=True)
        src = os.path.join('/tmp/blender-shots', s['name'])
        if os.path.isdir(src) and not manifest_only:
            for f in os.listdir(d):
                os.remove(os.path.join(d, f))
            for f in sorted(os.listdir(src)):
                if not f.endswith('.png'):
                    continue
                im = Image.open(os.path.join(src, f))
                dst = os.path.join(d, f[:-4] + '.' + s['ext'])
                if s['ext'] == 'jpg':
                    im.convert('RGB').save(dst, quality=90, subsampling=0, optimize=True)
                else:
                    q = im.convert('RGBA').quantize(256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
                    q.save(dst, optimize=True)
        files = sorted(f for f in os.listdir(d) if f.endswith('.' + s['ext']))
        if not files:
            print('missing', s['name']); continue
        w, h = Image.open(os.path.join(d, files[0])).size
        size = sum(os.path.getsize(os.path.join(d, f)) for f in files)
        manifest.append(dict(name=s['name'], frames=len(files), fps=30, alpha=s['alpha'],
                             ext=s['ext'], x=s['x'], y=s['y'], w=s['w'], h=s['h'], src_w=w, src_h=h,
                             duration=round(len(files) / 30, 3), note=s['note']))
        print('%-12s %3d frames  %4dx%-4d  %.1f MB' % (s['name'], len(files), w, h, size / 1e6))
    with open(os.path.join(OUT, 'manifest.json'), 'w') as fh:
        json.dump(manifest, fh, indent=2)
    with open(os.path.join(OUT, 'manifest.js'), 'w') as fh:
        fh.write('// Generated by tools/blender/finalize.py. Do not edit by hand.\n'
                 '// Start times are NOT here: film/timeline.js "shots3d" anchors each shot as {ch, at}.\n'
                 'window.SHOTS3D_MANIFEST = ' + json.dumps(manifest, indent=2) + ';\n')
    print('wrote', os.path.join(OUT, 'manifest.json'), 'and manifest.js')


if __name__ == '__main__':
    main()
